name: CI/CD - Build, Push, Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend
        run: |
          docker build -f backend/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/lemp-backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lemp-backend:latest

      - name: Build & push frontend
        run: |
          docker build -f frontend/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/lemp-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lemp-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH into VM and update containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_SSH_HOST }}
          username: ${{ secrets.VM_SSH_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -e
            cd ${{ secrets.APP_DIR }}

            # ensure env has your Docker Hub username
            if grep -q '^DOCKERHUB_USERNAME=' .env; then
              sed -i "s/^DOCKERHUB_USERNAME=.*/DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}/" .env
            else
              echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env
            fi

            # stop dev stack if running; free port 80 if needed
            docker compose -f docker-compose.dev.yml down || true
            sudo systemctl stop apache2 nginx 2>/dev/null || true

            # pull fresh images and restart prod
            docker compose -f docker-compose.prod.yml --env-file .env pull
            docker compose -f docker-compose.prod.yml --env-file .env up -d

            docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Ports}}"


